[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "eunomia"
version = "1.0.0"
authors = [
  { name="David J Owens", email="davidjayowens+eunomia@gmail.com" },
]
description = "Analyzes state-level legislation via NLP and cluster analysis. Uses bill texts from Legiscan."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "CC-BY-NC-SA-4.0"
license-files = ["LICEN[CS]E*"]
dependencies = [
  "requests",
  "pandas",
  "nltk",
  "scikit-learn",
  "plotly",
  "bs4",
  "tika",
  "striprtf",
  "pymongo"
]

[project.urls]
Homepage = "https://github.com/davidjayowens/eunomia"
Issues = "https://github.com/davidjayowens/eunomia/issues"